#!/usr/bin/bash
toplevel=$(git rev-parse --show-superproject-working-tree)
#if [ x"$toplevel" != "" ]; then
#    (cd "$toplevel"; git push);
#fi
git submodule foreach 'if [ -e $toplevel/g/bin/pre-push-hook ]; then $toplevel/g/bin/pre-push-hook $toplevel/g/push-branches.txt; else :; fi'
