#!/usr/bin/bash
toplevel=$(git rev-parse --show-superproject-working-tree)
if [ x"$IN_RECURSIVE_PUSH" = x ] && [ x"$toplevel" != x ]; then
    # do not add IN_RECURSIVE_PUSH=1 here, we want to make it to the
    # toplevel (confusingly, $toplevel is only the immediate parent's
    # toplevel)
    # echo "Recursing into $toplevel"
    # (cd "$toplevel"; git push || exit 1)
    :
fi
[ -e g/canonical.txt ] && IN_RECURSIVE_PUSH=1 g/bin/push-canon
[ -e g/remotes.txt ] && IN_RECURSIVE_PUSH=1 g/bin/push-remotes
# [ -e g/canonical.txt ] && IN_RECURSIVE_PUSH=1 g/bin/fetch-canon
# [ -e g/remotes.txt ] && IN_RECURSIVE_PUSH=1 g/bin/fetch-upstream
